include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: false
    strict-raw-types: false
  exclude:
    - '**/*.mocks.dart'

linter:
  rules:
    prefer_single_quotes: false
    unawaited_futures: false